# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/home/alan/puydufou/training-terraform/exercises/terragrunt/training/layers/../states/pets/staging/terraform.tfstate"
  }
}
