# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/home/alan/puydufou/training-terraform/exercises/terragrunt/solution/layers/../states/other-pets/prod/terraform.tfstate"
  }
}
